/**
 * Automatically generated by Zserio C++ extension version 2.0.0-pre1.
 */

#ifndef PMR_POC_BIG_STRUCT_H
#define PMR_POC_BIG_STRUCT_H

#include <zserio/BitStreamReader.h>
#include <zserio/BitStreamWriter.h>
#include <zserio/PreWriteAction.h>
#include <zserio/Types.h>

namespace pmr_poc
{

class BigStruct
{
public:
    explicit BigStruct(::zserio::BitStreamReader& in);

    ~BigStruct() = default;

    BigStruct(const BigStruct&) = default;
    BigStruct& operator=(const BigStruct&) = default;

    BigStruct(BigStruct&&) = default;
    BigStruct& operator=(BigStruct&&) = default;

    uint64_t getField1() const;

    uint64_t getField2() const;

    uint64_t getField3() const;

    uint64_t getField4() const;

    uint64_t getField5() const;

    uint64_t getField6() const;

    uint64_t getField7() const;

    uint64_t getField8() const;

    size_t bitSizeOf(size_t bitPosition = 0) const;

    bool operator==(const BigStruct& other) const;
    int hashCode() const;

private:
    uint64_t readField1(::zserio::BitStreamReader& in);
    uint64_t readField2(::zserio::BitStreamReader& in);
    uint64_t readField3(::zserio::BitStreamReader& in);
    uint64_t readField4(::zserio::BitStreamReader& in);
    uint64_t readField5(::zserio::BitStreamReader& in);
    uint64_t readField6(::zserio::BitStreamReader& in);
    uint64_t readField7(::zserio::BitStreamReader& in);
    uint64_t readField8(::zserio::BitStreamReader& in);

    uint64_t m_field1_;
    uint64_t m_field2_;
    uint64_t m_field3_;
    uint64_t m_field4_;
    uint64_t m_field5_;
    uint64_t m_field6_;
    uint64_t m_field7_;
    uint64_t m_field8_;
};

} // namespace pmr_poc

#endif // PMR_POC_BIG_STRUCT_H
