/**
 * Automatically generated by Zserio C++ extension version 2.0.0-pre1.
 */

#include <zserio/StringConvertUtil.h>
#include <zserio/CppRuntimeException.h>
#include <zserio/HashCodeUtil.h>
#include <zserio/BitPositionUtil.h>
#include <zserio/BitSizeOfCalculator.h>
#include <zserio/BitFieldUtil.h>

#include <pmr_poc/SampleStruct.h>

namespace pmr_poc
{

SampleStruct::SampleStruct(::zserio::BitStreamReader& in, ::zserio::pmr::MemoryResource& resource) :
        m_uint8Field_(readUint8Field(in)),
        m_stringField_(readStringField(in, resource)),
        m_childField_(readChildField(in, resource))
{
}

uint8_t SampleStruct::getUint8Field() const
{
    return m_uint8Field_;
}

const ::zserio::pmr::string& SampleStruct::getStringField() const
{
    return m_stringField_;
}

const ::pmr_poc::ChildStruct& SampleStruct::getChildField() const
{
    return m_childField_;
}

size_t SampleStruct::bitSizeOf(size_t bitPosition) const
{
    size_t endBitPosition = bitPosition;

    endBitPosition += UINT8_C(8);
    endBitPosition += ::zserio::bitSizeOfString(m_stringField_);
    endBitPosition += m_childField_.bitSizeOf(endBitPosition);

    return endBitPosition - bitPosition;
}

bool SampleStruct::operator==(const SampleStruct& other) const
{
    if (this != &other)
    {
        return
                (m_uint8Field_ == other.m_uint8Field_) &&
                (m_stringField_ == other.m_stringField_) &&
                (m_childField_ == other.m_childField_);
    }

    return true;
}

int SampleStruct::hashCode() const
{
    int result = ::zserio::HASH_SEED;

    result = ::zserio::calcHashCode(result, m_uint8Field_);
    result = ::zserio::calcHashCode(result, m_stringField_);
    result = ::zserio::calcHashCode(result, m_childField_);

    return result;
}

uint8_t SampleStruct::readUint8Field(::zserio::BitStreamReader& in)
{
    return static_cast<uint8_t>(in.readBits(UINT8_C(8)));
}

::zserio::pmr::string SampleStruct::readStringField(::zserio::BitStreamReader& in,
        ::zserio::pmr::MemoryResource& resource)
{
    return in.readString<::zserio::pmr::PolymorphicAllocator>(resource);
}

::pmr_poc::ChildStruct SampleStruct::readChildField(::zserio::BitStreamReader& in,
        ::zserio::pmr::MemoryResource& resource)
{
    return ::pmr_poc::ChildStruct(in, resource);
}

} // namespace pmr_poc
